// <auto-generated />
using System;
using JdCat.Cat.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JdCat.Cat.Model.Migrations
{
    [DbContext(typeof(CatDbContext))]
    [Migration("20191101030249_Modify_SaleReturnCoupon_Name")]
    partial class Modify_SaleReturnCoupon_Name
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("JdCat.Cat.Model.Data.Address", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AreaName");

                    b.Property<string>("CityName");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("DetailInfo");

                    b.Property<int>("Gender");

                    b.Property<double>("Lat");

                    b.Property<double>("Lng");

                    b.Property<string>("MapInfo");

                    b.Property<DateTime>("ModifyTime");

                    b.Property<string>("Phone");

                    b.Property<string>("PostalCode");

                    b.Property<string>("ProvinceName");

                    b.Property<string>("Receiver");

                    b.Property<int>("UserId");

                    b.HasKey("ID");

                    b.HasIndex("UserId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.BoothProductRelative", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreateTime");

                    b.Property<int>("ProductId");

                    b.Property<int>("StoreBoothId");

                    b.HasKey("ID");

                    b.HasIndex("ProductId");

                    b.HasIndex("StoreBoothId");

                    b.ToTable("BoothProductRelative");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.Business", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("AppId");

                    b.Property<string>("AppQrCode");

                    b.Property<string>("Area");

                    b.Property<string>("BusinessEndTime");

                    b.Property<string>("BusinessEndTime2");

                    b.Property<string>("BusinessEndTime3");

                    b.Property<string>("BusinessLicense");

                    b.Property<string>("BusinessLicenseImage");

                    b.Property<string>("BusinessStartTime");

                    b.Property<string>("BusinessStartTime2");

                    b.Property<string>("BusinessStartTime3");

                    b.Property<int>("Category");

                    b.Property<string>("CertFile");

                    b.Property<string>("City");

                    b.Property<string>("CityCode");

                    b.Property<string>("CityName");

                    b.Property<string>("Code");

                    b.Property<string>("Contact");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("DadaShopNo");

                    b.Property<string>("DadaSourceId");

                    b.Property<string>("DefaultPrinterDevice");

                    b.Property<double>("Delivery");

                    b.Property<string>("Description");

                    b.Property<int>("DiscountQuantity");

                    b.Property<long?>("Eleme_AppId");

                    b.Property<string>("Eleme_AppKey");

                    b.Property<string>("Eleme_AppSecret");

                    b.Property<long?>("Eleme_Poi_Id");

                    b.Property<string>("Email");

                    b.Property<string>("FeyinApiKey");

                    b.Property<string>("FeyinMemberCode");

                    b.Property<double?>("Freight");

                    b.Property<int>("FreightMode");

                    b.Property<string>("InvitationCode");

                    b.Property<bool>("IsAutoReceipt");

                    b.Property<bool>("IsClose");

                    b.Property<bool>("IsEnjoymentActivity");

                    b.Property<bool>("IsPublish");

                    b.Property<double>("Lat");

                    b.Property<double>("Lng");

                    b.Property<string>("LogoSrc");

                    b.Property<string>("MT_AppId");

                    b.Property<string>("MT_AppKey");

                    b.Property<bool>("MT_AutoRecieved");

                    b.Property<int>("MT_DeliveryMode");

                    b.Property<bool>("MT_IsDelivery");

                    b.Property<string>("MT_Poi_Id");

                    b.Property<string>("MchId");

                    b.Property<string>("MchKey");

                    b.Property<double>("MinAmount");

                    b.Property<string>("Mobile");

                    b.Property<string>("Name");

                    b.Property<string>("NewOrderTemplateId");

                    b.Property<string>("ObjectId");

                    b.Property<int?>("ParentId");

                    b.Property<string>("Password");

                    b.Property<string>("PayServerAppId");

                    b.Property<string>("PayServerKey");

                    b.Property<string>("PayServerMchId");

                    b.Property<string>("Province");

                    b.Property<double>("Range");

                    b.Property<string>("RefundTemplateId");

                    b.Property<DateTime?>("RegisterDate");

                    b.Property<double>("Score");

                    b.Property<string>("Secret");

                    b.Property<int>("ServiceProvider");

                    b.Property<string>("ShunfengDevId");

                    b.Property<string>("ShunfengDevKey");

                    b.Property<string>("ShunfengShopId");

                    b.Property<string>("SpecialImage");

                    b.Property<string>("StoreId");

                    b.Property<string>("TemplateNotifyId");

                    b.Property<string>("WeChatAppId");

                    b.Property<string>("WeChatSecret");

                    b.Property<string>("WxQrListenPath");

                    b.Property<string>("YcfkKey");

                    b.Property<string>("YcfkSecret");

                    b.HasKey("ID");

                    b.HasIndex("ParentId");

                    b.ToTable("Business");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.BusinessFreight", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Amount");

                    b.Property<int>("BusinessId");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<double>("MaxDistance");

                    b.Property<DateTime?>("ModifyTime");

                    b.HasKey("ID");

                    b.HasIndex("BusinessId");

                    b.ToTable("BusinessFreight");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.CardBonusRule", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Amount");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<double>("Give");

                    b.Property<int>("Mode");

                    b.Property<int>("WxCardId");

                    b.HasKey("ID");

                    b.HasIndex("WxCardId");

                    b.ToTable("CardBonusRule");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.CardChargeRule", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Amount");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<double>("Give");

                    b.Property<int>("WxCardId");

                    b.HasKey("ID");

                    b.HasIndex("WxCardId");

                    b.ToTable("CardChargeRule");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.ChargeRecord", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Amount");

                    b.Property<int>("Bonus");

                    b.Property<int>("BusinessId");

                    b.Property<string>("Code");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<int>("Give");

                    b.Property<string>("OpenId");

                    b.Property<DateTime?>("PayTime");

                    b.Property<string>("PrepayId");

                    b.Property<int>("RelativeId");

                    b.Property<int>("Status");

                    b.Property<string>("WxPayCode");

                    b.HasKey("ID");

                    b.HasIndex("BusinessId");

                    b.ToTable("ChargeRecord");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.City", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("City");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.ClientPrinter", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BusinessId");

                    b.Property<string>("CashierName");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("FoodIds");

                    b.Property<int>("Format");

                    b.Property<string>("IP");

                    b.Property<int>("Mode");

                    b.Property<string>("Name");

                    b.Property<int>("Port");

                    b.Property<int>("Quantity");

                    b.Property<int>("Scope");

                    b.Property<int>("State");

                    b.Property<int>("Type");

                    b.HasKey("ID");

                    b.HasIndex("BusinessId");

                    b.ToTable("ClientPrinter");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.CookProductRelative", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreateTime");

                    b.Property<int>("ProductId");

                    b.Property<int>("StaffId");

                    b.HasKey("ID");

                    b.HasIndex("ProductId");

                    b.HasIndex("StaffId");

                    b.ToTable("CookProductRelative");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.DWDStore", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BusinessId");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("addr");

                    b.Property<string>("city_code");

                    b.Property<string>("city_name");

                    b.Property<string>("external_shopid");

                    b.Property<double>("lat");

                    b.Property<double>("lng");

                    b.Property<string>("mobile");

                    b.Property<string>("shop_title");

                    b.HasKey("ID");

                    b.HasIndex("BusinessId")
                        .IsUnique();

                    b.ToTable("DWDStore");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.DWD_Recharge", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Amount");

                    b.Property<string>("Code");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<int>("DWD_BusinessId");

                    b.Property<string>("DwdCode");

                    b.Property<bool>("IsFinish");

                    b.Property<int>("Mode");

                    b.HasKey("ID");

                    b.HasIndex("DWD_BusinessId");

                    b.ToTable("DWD_Recharge");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.DadaCallBack", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreateTime");

                    b.Property<int>("OrderId");

                    b.Property<int>("cancel_from");

                    b.Property<string>("cancel_reason");

                    b.Property<string>("client_id");

                    b.Property<int>("dm_id");

                    b.Property<string>("dm_mobile");

                    b.Property<string>("dm_name");

                    b.Property<string>("order_id");

                    b.Property<int>("order_status");

                    b.Property<string>("signature");

                    b.Property<int>("update_time");

                    b.HasKey("ID");

                    b.HasIndex("OrderId");

                    b.ToTable("DadaCallBack");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.DadaCancelReason", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreateTime");

                    b.Property<int>("FlagId");

                    b.Property<string>("Reason");

                    b.HasKey("ID");

                    b.ToTable("DadaCancelReason");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.DadaLiquidatedDamages", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreateTime");

                    b.Property<double>("Deduct_fee");

                    b.Property<int>("OrderId");

                    b.HasKey("ID");

                    b.HasIndex("OrderId");

                    b.ToTable("DadaLiquidatedDamages");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.DadaReturn", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<double?>("CouponFee");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<double>("DeliverFee");

                    b.Property<double>("Distance");

                    b.Property<double>("Fee");

                    b.Property<double?>("InsuranceFee");

                    b.Property<int>("OrderId");

                    b.Property<double?>("Tips");

                    b.HasKey("ID");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("DadaReturn");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.Desk", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BusinessId");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<int>("DeskTypeId");

                    b.Property<string>("Name");

                    b.Property<int>("Quantity");

                    b.Property<int>("Status");

                    b.HasKey("ID");

                    b.HasIndex("BusinessId");

                    b.HasIndex("DeskTypeId");

                    b.ToTable("Desk");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.DeskType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BusinessId");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("Name");

                    b.Property<int>("Sort");

                    b.Property<int>("Status");

                    b.HasKey("ID");

                    b.HasIndex("BusinessId");

                    b.ToTable("DeskType");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.FeyinDevice", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApiKey");

                    b.Property<int>("BusinessId");

                    b.Property<string>("Code");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<bool>("IsDefault");

                    b.Property<string>("MemberCode");

                    b.Property<string>("Name");

                    b.Property<string>("Remark");

                    b.Property<int>("Type");

                    b.HasKey("ID");

                    b.HasIndex("BusinessId");

                    b.ToTable("FeyinDevice");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.ImageWarehouse", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreateTime");

                    b.Property<int>("ImageType");

                    b.Property<int>("RelativeId");

                    b.Property<string>("Src");

                    b.HasKey("ID");

                    b.ToTable("ImageWarehouse");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.OpenAuthInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AppId");

                    b.Property<string>("AuthNote");

                    b.Property<int>("BusinessId");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<DateTime?>("ModifyTime");

                    b.Property<string>("RefreshToken");

                    b.HasKey("ID");

                    b.HasIndex("BusinessId");

                    b.ToTable("OpenAuthInfo");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("AchieveTime");

                    b.Property<int?>("BusinessId");

                    b.Property<double?>("CallbackCost");

                    b.Property<string>("CancelReason");

                    b.Property<int>("Category");

                    b.Property<string>("CityCode");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<int>("DeliveryMode");

                    b.Property<DateTime?>("DeliveryTime");

                    b.Property<int?>("Distance");

                    b.Property<int>("DistributionFlow");

                    b.Property<string>("DistributionId");

                    b.Property<DateTime?>("DistributionTime");

                    b.Property<string>("ErrorReason");

                    b.Property<double?>("Freight");

                    b.Property<int>("Gender");

                    b.Property<int>("Identifier");

                    b.Property<string>("InvoiceName");

                    b.Property<string>("InvoiceTax");

                    b.Property<bool>("IsSendDada");

                    b.Property<double>("Lat");

                    b.Property<double>("Lng");

                    b.Property<int>("LogisticsType");

                    b.Property<double?>("OldPrice");

                    b.Property<string>("OpenId");

                    b.Property<string>("OrderCode");

                    b.Property<double?>("PackagePrice");

                    b.Property<DateTime?>("PayTime");

                    b.Property<int>("PaymentType");

                    b.Property<string>("Phone");

                    b.Property<string>("PrepayId");

                    b.Property<double?>("Price");

                    b.Property<string>("ReceiverAddress");

                    b.Property<string>("ReceiverName");

                    b.Property<string>("RefundNo");

                    b.Property<string>("RefundReason");

                    b.Property<int>("RefundStatus");

                    b.Property<DateTime?>("RefundTime");

                    b.Property<string>("RejectReasion");

                    b.Property<string>("Remark");

                    b.Property<int?>("SaleCouponUserId");

                    b.Property<double?>("SaleCouponUserMoney");

                    b.Property<int?>("SaleFullReduceId");

                    b.Property<double?>("SaleFullReduceMoney");

                    b.Property<int>("Status");

                    b.Property<int?>("TablewareQuantity");

                    b.Property<int>("Times");

                    b.Property<double?>("Tips");

                    b.Property<int>("Type");

                    b.Property<int?>("UserId");

                    b.Property<string>("WxPayCode");

                    b.HasKey("ID");

                    b.HasIndex("BusinessId");

                    b.HasIndex("SaleCouponUserId")
                        .IsUnique();

                    b.HasIndex("SaleFullReduceId");

                    b.HasIndex("UserId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.OrderActivity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ActivityId");

                    b.Property<double>("Amount");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<int>("OrderId");

                    b.Property<string>("Remark");

                    b.Property<int>("Type");

                    b.HasKey("ID");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderActivity");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.OrderComment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("ActualTime");

                    b.Property<DateTime>("ArrivedTime");

                    b.Property<int>("BusinessId");

                    b.Property<string>("CommentContent");

                    b.Property<string>("CommentResult");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("DeliveryResult");

                    b.Property<int>("DeliveryScore");

                    b.Property<int>("DeliveryType");

                    b.Property<string>("Face");

                    b.Property<bool>("IsShow");

                    b.Property<int>("OrderId");

                    b.Property<int>("OrderScore");

                    b.Property<string>("Phone");

                    b.Property<string>("ReplyContent");

                    b.Property<DateTime?>("ReplyTime");

                    b.Property<int>("UserId");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.HasIndex("BusinessId");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("OrderComment");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.OrderProduct", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CommentResult");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("Description");

                    b.Property<double?>("Discount");

                    b.Property<int?>("DiscountProductQuantity");

                    b.Property<int>("Feature");

                    b.Property<int?>("FormatId");

                    b.Property<string>("Name");

                    b.Property<double?>("OldPrice");

                    b.Property<int?>("OrderCommentId");

                    b.Property<int>("OrderId");

                    b.Property<double?>("Price");

                    b.Property<int?>("ProductId");

                    b.Property<string>("ProductIdSet");

                    b.Property<double?>("Quantity");

                    b.Property<int?>("SaleProductDiscountId");

                    b.Property<string>("Src");

                    b.HasKey("ID");

                    b.HasIndex("FormatId");

                    b.HasIndex("OrderCommentId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleProductDiscountId");

                    b.ToTable("OrderProduct");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.PaymentTarget", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<int>("ObjectId");

                    b.Property<int>("OrderId");

                    b.Property<int>("Status");

                    b.HasKey("ID");

                    b.ToTable("PaymentTarget");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.PaymentType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BusinessId");

                    b.Property<int>("Category");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("Name");

                    b.Property<int>("Sort");

                    b.Property<int>("Status");

                    b.HasKey("ID");

                    b.HasIndex("BusinessId");

                    b.ToTable("PaymentType");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BusinessId");

                    b.Property<string>("Code");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("Description");

                    b.Property<int>("Feature");

                    b.Property<string>("FirstLetter");

                    b.Property<bool>("IsDiscount");

                    b.Property<double?>("MinBuyQuantity");

                    b.Property<DateTime?>("ModifyTime");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTime?>("NotSaleTime");

                    b.Property<string>("Pinyin");

                    b.Property<string>("ProductIdSet");

                    b.Property<int?>("ProductTypeId");

                    b.Property<DateTime?>("PublishTime");

                    b.Property<int>("Scope");

                    b.Property<int>("Status");

                    b.Property<string>("Tag");

                    b.Property<string>("UnitName");

                    b.HasKey("ID");

                    b.HasIndex("BusinessId");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.ProductAttribute", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("Item1");

                    b.Property<string>("Item2");

                    b.Property<string>("Item3");

                    b.Property<string>("Item4");

                    b.Property<string>("Item5");

                    b.Property<string>("Item6");

                    b.Property<string>("Item7");

                    b.Property<string>("Item8");

                    b.Property<string>("Name");

                    b.Property<int>("ProductId");

                    b.HasKey("ID");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductAttribute");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.ProductFormat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<bool>("IsDelete");

                    b.Property<string>("Name");

                    b.Property<double?>("PackingPrice");

                    b.Property<double?>("PackingQuantity");

                    b.Property<string>("Position");

                    b.Property<double?>("Price");

                    b.Property<int>("ProductId");

                    b.Property<string>("SKU");

                    b.Property<double?>("Stock");

                    b.Property<string>("UPC");

                    b.HasKey("ID");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductFormat");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.ProductImage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("ExtensionName");

                    b.Property<long>("Length");

                    b.Property<string>("Name");

                    b.Property<int>("ProductId");

                    b.Property<int>("Type");

                    b.HasKey("ID");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImage");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.ProductRelative", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreateTime");

                    b.Property<int>("ProductId");

                    b.Property<int>("SetMealId");

                    b.HasKey("ID");

                    b.ToTable("ProductRelative");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.ProductType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BusinessId");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Sort");

                    b.HasKey("ID");

                    b.HasIndex("BusinessId");

                    b.ToTable("ProductType");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.SaleCoupon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BusinessId");

                    b.Property<int>("Consumed");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<DateTime?>("EndDate");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDelete");

                    b.Property<double>("MinConsume");

                    b.Property<string>("Name");

                    b.Property<int>("Quantity");

                    b.Property<int>("Received");

                    b.Property<DateTime?>("StartDate");

                    b.Property<int>("Stock");

                    b.Property<int?>("ValidDay");

                    b.Property<double>("Value");

                    b.HasKey("ID");

                    b.HasIndex("BusinessId");

                    b.ToTable("SaleCoupon");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.SaleCouponUser", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<int>("CouponId");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<DateTime?>("EndDate");

                    b.Property<double>("MinConsume");

                    b.Property<string>("Name");

                    b.Property<int?>("OrderId");

                    b.Property<DateTime?>("StartDate");

                    b.Property<int>("Status");

                    b.Property<DateTime?>("UseTime");

                    b.Property<int>("UserId");

                    b.Property<int?>("ValidDay");

                    b.Property<double>("Value");

                    b.HasKey("ID");

                    b.HasIndex("CouponId");

                    b.HasIndex("UserId");

                    b.ToTable("SaleCouponUser");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.SaleFullReduce", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BusinessId");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<DateTime?>("EndDate");

                    b.Property<bool>("IsDelete");

                    b.Property<bool>("IsForeverValid");

                    b.Property<double>("MinPrice");

                    b.Property<DateTime?>("ModifyTime");

                    b.Property<string>("Name");

                    b.Property<double>("ReduceMoney");

                    b.Property<DateTime?>("StartDate");

                    b.HasKey("ID");

                    b.HasIndex("BusinessId");

                    b.ToTable("SaleFullReduce");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.SaleNewCustom", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Amount");

                    b.Property<int>("BusinessId");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<DateTime>("EndTime");

                    b.Property<DateTime>("StartTime");

                    b.HasKey("ID");

                    b.HasIndex("BusinessId");

                    b.ToTable("SaleNewCustom");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.SaleProductDiscount", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BusinessId");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<int>("Cycle");

                    b.Property<double>("Discount");

                    b.Property<DateTime?>("EndDate");

                    b.Property<string>("EndTime1");

                    b.Property<string>("EndTime2");

                    b.Property<string>("EndTime3");

                    b.Property<string>("Name");

                    b.Property<double>("OldPrice");

                    b.Property<double>("Price");

                    b.Property<int>("ProductId");

                    b.Property<string>("SettingType");

                    b.Property<DateTime?>("StartDate");

                    b.Property<string>("StartTime1");

                    b.Property<string>("StartTime2");

                    b.Property<string>("StartTime3");

                    b.Property<int>("Status");

                    b.Property<int>("UpperLimit");

                    b.HasKey("ID");

                    b.HasIndex("BusinessId");

                    b.HasIndex("ProductId");

                    b.ToTable("SaleProductDiscount");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.SaleReturnCoupon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BusinessId");

                    b.Property<int>("Consumed");

                    b.Property<double>("CostAmount");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<DateTime?>("EndDate");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDelete");

                    b.Property<double>("MinConsume");

                    b.Property<string>("Name");

                    b.Property<int>("Quantity");

                    b.Property<int>("Received");

                    b.Property<DateTime?>("StartDate");

                    b.Property<int>("Stock");

                    b.Property<int?>("ValidDay");

                    b.Property<double>("Value");

                    b.HasKey("ID");

                    b.HasIndex("BusinessId");

                    b.ToTable("SaleReturnCoupon");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.SessionData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("SessionKey");

                    b.Property<int>("UserId");

                    b.HasKey("ID");

                    b.HasIndex("UserId");

                    b.ToTable("SessionData");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.SettingProductAttribute", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreateTime");

                    b.Property<int>("Level");

                    b.Property<string>("Name");

                    b.Property<int?>("ParentId");

                    b.Property<int>("Sort");

                    b.HasKey("ID");

                    b.HasIndex("ParentId");

                    b.ToTable("SettingProductAttribute");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.ShoppingCart", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("BusinessId");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("Description");

                    b.Property<int>("FormatId");

                    b.Property<string>("Name");

                    b.Property<int>("PackingQuantity");

                    b.Property<double?>("Price");

                    b.Property<int>("ProductId");

                    b.Property<int>("Quantity");

                    b.Property<string>("Src");

                    b.Property<int>("UserId");

                    b.HasKey("ID");

                    b.HasIndex("BusinessId");

                    b.HasIndex("FormatId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("ShoppingCart");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.Staff", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Alise");

                    b.Property<DateTime?>("Birthday");

                    b.Property<int>("BusinessId");

                    b.Property<string>("CardId");

                    b.Property<string>("Code");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<DateTime?>("EnterTime");

                    b.Property<int>("Gender");

                    b.Property<DateTime?>("ModifyTime");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<int>("StaffPostId");

                    b.Property<int>("Status");

                    b.HasKey("ID");

                    b.HasIndex("BusinessId");

                    b.HasIndex("StaffPostId");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.StaffPost", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Authority");

                    b.Property<int>("BusinessId");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<DateTime?>("ModifyTime");

                    b.Property<string>("Name");

                    b.Property<int>("Status");

                    b.HasKey("ID");

                    b.HasIndex("BusinessId");

                    b.ToTable("StaffPost");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.StoreBooth", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BusinessId");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.HasIndex("BusinessId");

                    b.ToTable("StoreBooth");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.SystemMark", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BusinessId");

                    b.Property<int>("Category");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.HasIndex("BusinessId");

                    b.ToTable("SystemMark");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.TangOrder", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("ActualAmount");

                    b.Property<double>("Amount");

                    b.Property<int>("BusinessId");

                    b.Property<string>("CancelReason");

                    b.Property<string>("CashierName");

                    b.Property<string>("Code");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<int?>("DeskId");

                    b.Property<string>("DeskName");

                    b.Property<int>("Identifier");

                    b.Property<double>("MealFee");

                    b.Property<DateTime>("ModifyTime");

                    b.Property<string>("ObjectId");

                    b.Property<double>("OrderDiscount");

                    b.Property<int>("OrderMode");

                    b.Property<int>("OrderSource");

                    b.Property<int>("OrderStatus");

                    b.Property<double>("OriginalAmount");

                    b.Property<DateTime?>("PayTime");

                    b.Property<string>("PaymentRemark");

                    b.Property<int>("PeopleNumber");

                    b.Property<double>("PreferentialAmount");

                    b.Property<string>("Remark");

                    b.Property<int?>("StaffId");

                    b.Property<string>("StaffName");

                    b.Property<int>("Status");

                    b.Property<DateTime>("SyncTime");

                    b.Property<double>("Tips");

                    b.HasKey("ID");

                    b.HasIndex("BusinessId");

                    b.HasIndex("DeskId");

                    b.HasIndex("StaffId");

                    b.ToTable("TangOrder");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.TangOrderActivity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ActivityId");

                    b.Property<double>("Amount");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<DateTime>("ModifyTime");

                    b.Property<string>("ObjectId");

                    b.Property<string>("Remark");

                    b.Property<int>("Status");

                    b.Property<DateTime>("SyncTime");

                    b.Property<int>("TangOrderId");

                    b.Property<string>("TangOrderObjectId");

                    b.Property<int>("Type");

                    b.HasKey("ID");

                    b.HasIndex("TangOrderId");

                    b.ToTable("TangOrderActivity");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.TangOrderPayment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Amount");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<DateTime>("ModifyTime");

                    b.Property<string>("Name");

                    b.Property<string>("ObjectId");

                    b.Property<string>("OrderObjectId");

                    b.Property<int>("PaymentTypeId");

                    b.Property<string>("PaymentTypeObjectId");

                    b.Property<int>("Status");

                    b.Property<DateTime>("SyncTime");

                    b.Property<int>("TangOrderId");

                    b.HasKey("ID");

                    b.HasIndex("PaymentTypeId");

                    b.HasIndex("TangOrderId");

                    b.ToTable("TangOrderPayment");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.TangOrderProduct", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Amount");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("Description");

                    b.Property<double>("Discount");

                    b.Property<int>("Feature");

                    b.Property<int>("FormatId");

                    b.Property<DateTime>("ModifyTime");

                    b.Property<string>("Name");

                    b.Property<string>("ObjectId");

                    b.Property<int>("OrderId");

                    b.Property<string>("OrderObjectId");

                    b.Property<double>("OriginalPrice");

                    b.Property<double>("Price");

                    b.Property<int>("ProductId");

                    b.Property<string>("ProductIdSet");

                    b.Property<int>("ProductStatus");

                    b.Property<double>("Quantity");

                    b.Property<string>("RefundReason");

                    b.Property<string>("Remark");

                    b.Property<string>("Src");

                    b.Property<int>("Status");

                    b.Property<DateTime>("SyncTime");

                    b.HasKey("ID");

                    b.HasIndex("FormatId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("TangOrderProduct");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.ThirdOrder", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Amount");

                    b.Property<int>("BusinessId");

                    b.Property<string>("Caution");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<DateTime>("Ctime");

                    b.Property<string>("Data1");

                    b.Property<string>("Data2");

                    b.Property<int>("DaySeq");

                    b.Property<DateTime?>("DeliveryTime");

                    b.Property<string>("Error");

                    b.Property<string>("InvoiceTitle");

                    b.Property<double>("Latitude");

                    b.Property<int>("LogisticsType");

                    b.Property<double>("Longitude");

                    b.Property<string>("OrderId");

                    b.Property<long>("OrderIdView");

                    b.Property<int>("OrderSource");

                    b.Property<double>("OriginalAmount");

                    b.Property<double>("PackageFee");

                    b.Property<string>("PoiAddress");

                    b.Property<string>("PoiCode");

                    b.Property<string>("PoiName");

                    b.Property<string>("PoiPhone");

                    b.Property<int>("PrintTimes");

                    b.Property<string>("Reason");

                    b.Property<string>("RecipientAddress");

                    b.Property<string>("RecipientName");

                    b.Property<string>("RecipientPhone");

                    b.Property<double>("ShippingFee");

                    b.Property<int>("Status");

                    b.Property<string>("TaxpayerId");

                    b.Property<DateTime>("Utime");

                    b.HasKey("ID");

                    b.HasIndex("BusinessId");

                    b.ToTable("ThirdOrder");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.ThirdOrderActivity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ActiveId");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<double>("PoiCharge");

                    b.Property<double>("ReduceFee");

                    b.Property<string>("Remark");

                    b.Property<double>("ThirdCharge");

                    b.Property<int>("ThirdOrderId");

                    b.Property<int>("Type");

                    b.HasKey("ID");

                    b.HasIndex("ThirdOrderId");

                    b.ToTable("ThirdOrderActivity");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.ThirdOrderProduct", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("BoxNum");

                    b.Property<double>("BoxPrice");

                    b.Property<int>("CartId");

                    b.Property<string>("Code");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("Description");

                    b.Property<double>("Discount");

                    b.Property<string>("Name");

                    b.Property<double>("Price");

                    b.Property<int>("ProductId");

                    b.Property<double>("Quantity");

                    b.Property<string>("SkuId");

                    b.Property<string>("Spec");

                    b.Property<int>("ThirdOrderId");

                    b.Property<string>("Unit");

                    b.HasKey("ID");

                    b.HasIndex("ThirdOrderId");

                    b.ToTable("ThirdOrderProduct");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.ThirdProductMapping", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BusinessId");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<int>("ProductId");

                    b.Property<string>("ThirdProductId");

                    b.Property<string>("ThirdProductName");

                    b.Property<int>("ThirdSource");

                    b.HasKey("ID");

                    b.HasIndex("BusinessId");

                    b.ToTable("ThirdProductMapping");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("AvatarUrl");

                    b.Property<int>("BusinessId");

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<int>("Gender");

                    b.Property<bool>("IsPhone");

                    b.Property<bool>("IsRegister");

                    b.Property<string>("Language");

                    b.Property<string>("NickName");

                    b.Property<string>("OpenId");

                    b.Property<string>("Phone");

                    b.Property<string>("Province");

                    b.Property<int>("PurchaseTimes");

                    b.HasKey("ID");

                    b.HasIndex("OpenId")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.WxCard", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BusinessId");

                    b.Property<string>("CardId");

                    b.Property<int>("Category");

                    b.Property<string>("Color");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("Name");

                    b.Property<int>("Status");

                    b.HasKey("ID");

                    b.HasIndex("BusinessId");

                    b.ToTable("WxCard");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.WxListenUser", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BusinessId");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("city");

                    b.Property<string>("country");

                    b.Property<string>("headimgurl");

                    b.Property<string>("nickname");

                    b.Property<string>("openid");

                    b.Property<string>("province");

                    b.Property<int>("sex");

                    b.HasKey("ID");

                    b.HasIndex("BusinessId");

                    b.ToTable("WxListenUser");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.WxMember", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Balance");

                    b.Property<DateTime>("Birthday");

                    b.Property<int>("Bonus");

                    b.Property<int>("BusinessId");

                    b.Property<string>("CardId");

                    b.Property<int>("ChargeTimes");

                    b.Property<string>("Code");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<int>("Gender");

                    b.Property<int>("GiveAmount");

                    b.Property<string>("Logo");

                    b.Property<string>("Name");

                    b.Property<string>("NickName");

                    b.Property<string>("OpenId");

                    b.Property<string>("Phone");

                    b.Property<int>("PurchaseTimes");

                    b.Property<int>("RechargeAmount");

                    b.Property<int>("WxCardId");

                    b.HasKey("ID");

                    b.HasIndex("BusinessId");

                    b.HasIndex("WxCardId");

                    b.ToTable("WxMember");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.YcfkLocation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreateTime");

                    b.Property<double>("Lat");

                    b.Property<double>("Lng");

                    b.Property<int>("OrderId");

                    b.HasKey("ID");

                    b.ToTable("YcfkLocation");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.Address", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.BoothProductRelative", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JdCat.Cat.Model.Data.StoreBooth", "StoreBooth")
                        .WithMany("BoothProductRelatives")
                        .HasForeignKey("StoreBoothId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.Business", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.Business", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.BusinessFreight", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.CardBonusRule", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.WxCard", "WxCard")
                        .WithMany()
                        .HasForeignKey("WxCardId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.CardChargeRule", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.WxCard", "WxCard")
                        .WithMany()
                        .HasForeignKey("WxCardId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.ChargeRecord", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.ClientPrinter", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.CookProductRelative", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JdCat.Cat.Model.Data.Staff", "Staff")
                        .WithMany("CookProductRelatives")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.DWDStore", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.Business", "Business")
                        .WithOne("DWDStore")
                        .HasForeignKey("JdCat.Cat.Model.Data.DWDStore", "BusinessId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.DWD_Recharge", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.DWDStore", "DWD_Business")
                        .WithMany("DWD_Recharges")
                        .HasForeignKey("DWD_BusinessId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.DadaCallBack", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.Order", "Order")
                        .WithMany("DadaCallBacks")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.DadaLiquidatedDamages", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.DadaReturn", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.Order", "Order")
                        .WithOne("DadaReturn")
                        .HasForeignKey("JdCat.Cat.Model.Data.DadaReturn", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.Desk", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JdCat.Cat.Model.Data.DeskType", "DeskType")
                        .WithMany("Desks")
                        .HasForeignKey("DeskTypeId");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.DeskType", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.FeyinDevice", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.Business", "Business")
                        .WithMany("FeyinDevices")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.OpenAuthInfo", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.Order", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.Business", "Business")
                        .WithMany("Orders")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JdCat.Cat.Model.Data.SaleCouponUser", "SaleCouponUser")
                        .WithOne("Order")
                        .HasForeignKey("JdCat.Cat.Model.Data.Order", "SaleCouponUserId");

                    b.HasOne("JdCat.Cat.Model.Data.SaleFullReduce", "SaleFullReduce")
                        .WithMany("Orders")
                        .HasForeignKey("SaleFullReduceId");

                    b.HasOne("JdCat.Cat.Model.Data.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.OrderActivity", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.Order", "Order")
                        .WithMany("OrderActivities")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.OrderComment", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JdCat.Cat.Model.Data.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JdCat.Cat.Model.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.OrderProduct", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.ProductFormat", "Format")
                        .WithMany("OrderProducts")
                        .HasForeignKey("FormatId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JdCat.Cat.Model.Data.OrderComment", "OrderComment")
                        .WithMany()
                        .HasForeignKey("OrderCommentId");

                    b.HasOne("JdCat.Cat.Model.Data.Order", "Order")
                        .WithMany("Products")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JdCat.Cat.Model.Data.Product", "Product")
                        .WithMany("OrderProducts")
                        .HasForeignKey("ProductId");

                    b.HasOne("JdCat.Cat.Model.Data.SaleProductDiscount", "SaleProductDiscount")
                        .WithMany()
                        .HasForeignKey("SaleProductDiscountId");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.PaymentType", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.Product", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.Business", "Business")
                        .WithMany("Products")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JdCat.Cat.Model.Data.ProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeId");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.ProductAttribute", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.Product", "Product")
                        .WithMany("Attributes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.ProductFormat", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.Product", "Product")
                        .WithMany("Formats")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.ProductImage", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.ProductType", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.Business", "Business")
                        .WithMany("ProductsTypes")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.SaleCoupon", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.SaleCouponUser", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.SaleCoupon", "Coupon")
                        .WithMany("CouponUsers")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JdCat.Cat.Model.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.SaleFullReduce", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.Business", "Business")
                        .WithMany("SaleFullReduces")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.SaleNewCustom", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.SaleProductDiscount", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.Business", "Business")
                        .WithMany("SaleProductDiscounts")
                        .HasForeignKey("BusinessId");

                    b.HasOne("JdCat.Cat.Model.Data.Product", "Product")
                        .WithMany("SaleProductDiscount")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.SaleReturnCoupon", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.SessionData", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.SettingProductAttribute", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.SettingProductAttribute", "Parent")
                        .WithMany("Childs")
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.ShoppingCart", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.Business", "Business")
                        .WithMany("ShoppingCarts")
                        .HasForeignKey("BusinessId");

                    b.HasOne("JdCat.Cat.Model.Data.ProductFormat", "Format")
                        .WithMany("ShoppingCarts")
                        .HasForeignKey("FormatId");

                    b.HasOne("JdCat.Cat.Model.Data.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JdCat.Cat.Model.Data.User", "User")
                        .WithMany("ShoppingCarts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.Staff", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JdCat.Cat.Model.Data.StaffPost", "StaffPost")
                        .WithMany("Staffs")
                        .HasForeignKey("StaffPostId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.StaffPost", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.StoreBooth", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.SystemMark", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.TangOrder", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JdCat.Cat.Model.Data.Desk", "Desk")
                        .WithMany()
                        .HasForeignKey("DeskId");

                    b.HasOne("JdCat.Cat.Model.Data.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId");
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.TangOrderActivity", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.TangOrder", "TangOrder")
                        .WithMany("TangOrderActivities")
                        .HasForeignKey("TangOrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.TangOrderPayment", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.PaymentType", "PaymentType")
                        .WithMany()
                        .HasForeignKey("PaymentTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JdCat.Cat.Model.Data.TangOrder", "TangOrder")
                        .WithMany("TangOrderPayments")
                        .HasForeignKey("TangOrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.TangOrderProduct", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.ProductFormat", "Format")
                        .WithMany()
                        .HasForeignKey("FormatId");

                    b.HasOne("JdCat.Cat.Model.Data.TangOrder", "TangOrder")
                        .WithMany("TangOrderProducts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JdCat.Cat.Model.Data.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.ThirdOrder", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.ThirdOrderActivity", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.ThirdOrder", "ThirdOrder")
                        .WithMany("ThirdOrderActivities")
                        .HasForeignKey("ThirdOrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.ThirdOrderProduct", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.ThirdOrder", "ThirdOrder")
                        .WithMany("ThirdOrderProducts")
                        .HasForeignKey("ThirdOrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.ThirdProductMapping", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.WxCard", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.WxListenUser", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JdCat.Cat.Model.Data.WxMember", b =>
                {
                    b.HasOne("JdCat.Cat.Model.Data.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JdCat.Cat.Model.Data.WxCard", "WxCard")
                        .WithMany()
                        .HasForeignKey("WxCardId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
